name: Generate CHANGELOG

on:
  push:
    branches:
      - feature/auto_tagging

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install packages
        run: |
          sudo snap install task --classic
          npm install -g auto-changelog

      - name: Generate CHANGELOG
        run: auto-changelog

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "CHANGELOG.md"
          message: "Update changelog"
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@gmail.com
